name: Deploy Static Next.js Build on PR Merge to Publish

on:
  # Runs on closed PR to publish branch
  push:
    branches:
      - publish
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js static site
        run: npm run build

      - name: Copy build files to server via SSH
      # Create out/ on server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CISA_HOST }}
          username: ${{ secrets.CISA_USERNAME }}
          password: ${{ secrets.CISA_PASSWORD }}
          source: ./out/* 
          target: ./
          rm: false
          
      - name: Move files and clean up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CISA_HOST }}
          username: ${{ secrets.CISA_USERNAME }}
          password: ${{ secrets.CISA_PASSWORD }}
          script: rm -r cisaconference/* && mv out/* cisaconference/ && rm -r out
